  const data = {
    products: [
      {
        _id: '1',
        name: 'ABC Speaker',
        category: 'Speaker',
        image: '/images/p1.jpg',
        price: 1200,
        countInStock: 10,
        brand: 'Xiaomi',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality product',
      },
      {
        _id: '2',
        name: 'ABC Speaker',
        category: 'Speaker',
        image: '/images/p2.jpg',
        price: 1000,
        countInStock: 5,
        brand: 'Xiaomi',
        rating: 4.0,
        numReviews: 10,
        description: 'high quality product',
      },
      {
        _id: '3',
        name: 'ABCD Speaker',
        category: 'Speaker',
        image: '/images/p3.jpg',
        price: 2200,
        countInStock: 0,
        brand: 'Xiaomi',
        rating: 4.8,
        numReviews: 17,
        description: 'high quality product',
      },
      {
        _id: '4',
        name: 'Ab speaker',
        category: 'speaker',
        image: '/images/p4.jpg',
        price: 7800,
        countInStock: 20,
        brand: 'Xiaomi',
        rating: 4.5,
        numReviews: 14,
        description: 'high quality product',
      },
      {
        _id: '5',
        name: 'ABC Headphones',
        category: 'Headphones',
        image: '/images/p5.jpg',
        price: 6500,
        countInStock: 90,
        brand: 'Xiaomi',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality product',
      },
      {
        _id: '6',
        name: 'AB Earphones',
        category: 'Pants',
        image: '/images/p6.jpg',
        price: 1390,
        countInStock: 4,
        brand: 'Xiaomi',
        rating: 4.5,
        numReviews: 15,
        description: 'high quality product',
      },
    ],
  };
  
  export default data;